<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>download Users</name>
   <tag></tag>
   <elementGuidId>bda8eff0-3ffe-4d3a-ae15-d1cfd1cf97ef</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>access-token</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>87a93ea8-fe26-49cd-ae1d-d5310ff9439d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>4ec2cfc3-c995-4ef3-9fdd-1a56753fdbd5</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.0.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${baseUrl}/:namespace/admin/users/report/download?createdAtFrom=&lt;dateTime>&amp;createdAtTo=&lt;dateTime>&amp;partialIdentifier=&lt;string>&amp;groupId=&lt;string>&amp;groupIds=&lt;string>&amp;groupIds=&lt;string>&amp;ids=&lt;string>&amp;ids=&lt;string>&amp;identifier=&lt;string>&amp;disabled=&lt;boolean>&amp;softDeleted=&lt;boolean>&amp;twoFaEnabled=&lt;boolean>&amp;timezone=Asia/Kuala_Lumpur</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseUrl</defaultValue>
      <description></description>
      <id>61eae993-1bc9-4e8e-9c90-ff7836b72b0b</id>
      <masked>false</masked>
      <name>baseUrl</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
